markdown: kramdown
plugins:
  - github-pages
remote_theme: rakutentech/android-buildconfig@gh-pages-theme

title: Remote Config SDK for Android
description: Provides remote configuration for Android applications.
repository: rakutentech/android-remote-config

docs_path: docs
api_docs_path: api

collections:
  versions:
