version: 2

gradle_cache_key: &gradle_cache_key gradle-{{ checksum "build.gradle" }}-{{ checksum "settings.gradle" }}

jobs:
  build:
    docker:
    - image: circleci/android:api-28
    working_directory: ~/code
    environment:
      JVM_OPTS: "-Xmx3200m"
    steps:
    - checkout
    - run: git submodule update --init
    - restore_cache:
        key: *gradle_cache_key
    - run:
        name: Run Tests
        command: ./gradlew check
    - run:
        name: Assemble
        command: ./gradlew assemble
    - save_cache:
        paths:
          - ~/.gradle
        key: *gradle_cache_key
    - store_artifacts:
        path: build/reports
        destination: reports/
    - store_test_results:
        path: build/test-results

